baseURL = "http://a-nakamura1015/gas-education"
languageCode = "ja"
title = "GAS Edu"
contentDir = "content"
disableKinds = ["RSS", "sitemap"]
publishDir = "docs"
theme = "hugo-theme-learn"

[taxonomies]
tag = "tags"

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
themeVariant = "blue"
customCSS = ["css/custom-font.css", "css/custom-table.css"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true
